name: Python Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'

    - name: Install dependencies
      run: |
        cd natter-extends
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install nuitka

    - name: Build with Nuitka
      run: |
        cd natter-extends
        mkdir -p dist
        nuitka --standalone --onefile --output-dir=dist --jobs=4 --disable-console --lto=yes notify.py

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: notify-build
        path: natter-extends/dist/
